clubManagement/urls.py
# created by Chirath R, chirath.02@gmail.com
from django.conf.urls import url

from clubManagement import views
from clubManagement.views import *
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(
        r'^attendance-report/(?P<year>[0-9]+)/$',
        login_required(YearAttendanceReportView.as_view()),
        name='attendance_report_year_all'
    ),
    url(
        r'^attendance-report/(?P<batch>[0-9]+)/(?P<year>[0-9]+)/$',
        login_required(YearAttendanceReportView.as_view()),
        name='attendance_report_year_batch'
    ),
    url(r'^attendance-report/(?P<batch>[0-9]+)/(?P<year>[0-9]+)/(?P<month>[0-9]+)/$',
        MonthAttendanceReportView.as_view(),
        name='attendance_report_month'
        ),
    url(
        r'^attendance-report-student/(?P<year>[0-9]+)/(?P<user_id>[0-9]+)/$',
        login_required(YearStudentAttendanceReportView.as_view()),
        name='attendance_report_year'
    ),
    url(
        r'^attendance/(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)/$',
        login_required(AttendanceAddView.as_view()),
        name='add_attendance_all'
    ),
    url(
        r'^attendance/(?P<batch>[0-9]+)/(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)/$',
        login_required(AttendanceAddView.as_view()),
        name='add_attendance_batch'
    ),

    # Responsibilities
    url(r'^responsibility/$', login_required(ResponsibilityListView.as_view()), name='responsibility'),
    url(r'^responsibility/(?P<pk>[0-9]+)/$', login_required(ResponsibilityDetailView.as_view()), name='responsibility_detail'),
    url(r'^responsibility/create/$', login_required(ResponsibilityCreateView.as_view()), name='responsibility_create'),
    url(r'^responsibility/(?P<pk>[0-9]+)/update/$', login_required(ResponsibilityUpdateView.as_view()), name='responsibility_update'),
    url(r'^responsibility/(?P<pk>[0-9]+)/delete/$', login_required(ResponsibilityDeleteView.as_view()), name='responsibility_delete'),
    url(r'^responsibility-student/(?P<pk>[0-9]+)/delete/$',
        StudentResponsibilityDeleteView.as_view(),
        name='student_responsibility_delete'
        ),

    # Teams
    url(r'^teams/$', TeamListView.as_view(), name='team'),
    url(r'^teams/(?P<pk>[0-9]+)/$', TeamDetailView.as_view(), name='team_detail'),
    url(r'^teams/create/$', login_required(TeamCreateView.as_view()), name='team_create'),
    url(r'^teams/(?P<pk>[0-9]+)/update$', login_required(TeamUpdateView.as_view()), name='team_update'),
    url(r'^teams/(?P<pk>[0-9]+)/delete/$', login_required(TeamDeleteView.as_view()), name='team_delete'),
    url(r'^teams-member/(?P<pk>[0-9]+)/delete/$', login_required(TeamMemberDeleteView.as_view()), name='team_member_delete'),

    # status report
    url(r'status/$', login_required(StatusListView.as_view()), name='status'),
    url(r'status/(?P<pk>[0-9]+)/$', login_required(StatusDetailView.as_view()), name='status_detail'),
    url(r'status/create/$', login_required(StatusCreateView.as_view()), name='status_create'),
    url(r'status/(?P<pk>[0-9]+)/update/$', login_required(StatusUpdateView.as_view()), name='status_update'),
    url(r'status/(?P<pk>[0-9]+)/delete/$', login_required(StatusDeleteView.as_view()), name='status_delete'),
    url(r'status-by-batch/(?P<pk>[0-9]+)/$', batchfilterview.as_view(), name='batch_filter'),
    # index
    url(r'^$', login_required(IndexView.as_view()), name='club'),
]

events/urls.py
from django.conf.urls import url

from events.forms import EventCreateForm
from events.views import EventCreateView, EventUpdateView, EventImageCreateView, EventImageUpdateView, EventDeleteView, \
    EventImageDeleteView, EventDetailView

urlpatterns = [
    url(r'^create/', EventCreateView.as_view(), name = "Event_add"),
    url(r'^edit/(?P<pk>[0-9]+)', EventUpdateView.as_view(), name = "Event_edit"),
    url(r'^addimage/', EventImageCreateView.as_view(), name = "eventimage_add"),
    url(r'^event/(?P<pk>[0-9]+)', EventDetailView.as_view(), name = "event_detail"),
    url(r'^editimage/(?P<pk>[0-9]+)', EventImageUpdateView.as_view(), name = "eventimage_edit"),
    url(r'^deleteimage/(?P<pk>[0-9]+)/', EventDeleteView.as_view(), name = "eventimage_delete"),
    url(r'^delete/(?P<pk>[0-9]+)', EventImageDeleteView.as_view(), name = "event_delete"),


]

fosswebsite/urls.py
# created by Chirath R, chirath.02@gmail.com
"""fosswebsite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from fosswebsite import settings
from .views import Home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Home.as_view(), name='home'),
    url(r'^accounts/', include('registration.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),#this file is invisible
    url(r'^club/', include('clubManagement.urls')),
    url(r'^foss/', include('promotion.urls')),
    url(r'^achievements/', include('achievements.urls')),
    url(r'^documents/', include('documents.urls')),
    url(r'^project/', include('projects.urls')),
    url(r'^timeline/', include('timeline.urls')),
    url(r'^workshop/', include('workshop.urls')),
    url(r'^notices/', include('noticeBoard.urls')),
    url(r'^resources/', include('technical_resources.urls')),
    url(r'^events/', include('events.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

clubManagement/models.py
# -*- coding: utf-8 -*-
# created by Chirath R, chirath.02@gmail.com
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from projects.models import Project


class Team(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='team/', blank=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('team_detail', kwargs={'pk': self.id})


class TeamMember(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    date_assigned = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.user.username + " - " + self.team.name


class Attendance(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    added_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="added_by")
    date = models.DateField()
    modified_date = models.DateTimeField(auto_now=True, auto_now_add=False)
    attendance = models.BooleanField(default=False)

    def __str__(self):
        if self.attendance:
            return self.user.username + " " + str(self.date) + " - present"
        else:
            return self.user.username + " " + str(self.date) + " - absent"


class Responsibility(models.Model):
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='created_by')
    name = models.CharField(max_length=300)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('responsibility_detail', kwargs={'pk': self.pk})


class StudentResponsibility(models.Model):
    responsibility = models.ForeignKey(Responsibility, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class StatusReport(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=300, null='True')
    date = models.DateTimeField(auto_now=False, auto_now_add=True)
    content = models.TextField()
    image = models.ImageField(upload_to='status_img/', blank=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.user.username + " " + self.content[:20] + ".."

    def get_absolute_url(self):
        return reverse('status_detail', kwargs={'pk': self.pk})

clubManagement/templates/clubManagement/attendance_add.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %} Add attendance {% endblock %}

{% block body %}
    {% include 'base/nav-bar.html' %}
    <div id="wrap">
        <div id="main">
            <div class="container">
                <form class="row" action="" method="post">
                    {% csrf_token %}
                    {% for attendance in attendance_list %}
                        <h2 class="header col-xs-12 col-md-12">{{ attendance.1 }}</h2>
                        {% for att in attendance.0 %}
                            <div class="col-xs-6 col-sm-4 col-md-2 btn names {% if att.attendance %}btn-success{% else %}btn-danger{% endif %}"
                                    {% if request.user.is_superuser %}
                                 onclick="click_attendance('{{ att.user.username }}')" {% endif %}
                                 id="{{ att.user.username }}_div" style="white-space: normal">
                                <p class="link">{{ att.user.first_name }} {{ att.user.last_name }}</p>
                                <input type="checkbox" style="display: None" id="{{ att.user.username }}" value="True"
                                       name="{{ att.user.username }}" {% if att.attendance %}checked{% endif %}>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    <p class="col-xs-12 col-md-12"></p>
                    <button type="reset" onclick="changeDay(-1)" class="col-md-2 col-sm-6 btn">Previous</button>
                    {% if request.user.is_superuser %}
                        <button type="submit" class="col-md-2 offset-md-3 col-sm-6 btn btn-primary save-btn">Save
                        </button>
                    {% endif %}
                    <button type="reset" onclick="changeDay(1)" class="col-md-2 offset-md-3 col-sm-6 btn">Next</button>
                </form>
            </div>
        </div>
    </div>

    {% include 'base/footer.html' %}

    <script>
        function changeDay(i) {
            var variables, year, month, day, link, date;

            variables = window.location.href.split("/");

            year = variables[(variables.length - 4)];
            month = variables[variables.length - 3] - 1;
            day = variables[variables.length - 2];

            if (variables.length === 9)
                link = '/club/attendance/';
            else
                link = '/club/attendance/' + parseInt(variables[variables.length - 5]) + '/';

            date = new Date(year, month, day, 0, 0, 0);
            date.setDate(date.getDate() + i);
            link += date.getFullYear() + '/' + (date.getMonth() + 1) + '/' + date.getDate();

            window.location = link;
        }
    </script>

    <style>
        .btn {
            margin: 10px;
        }

        .save-btn {
            padding: 10px 0;
        }

        .names {
            height: 80px;
        }

        .link {
            height: 100%;
            color: white;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        form {
            margin: 30px 0;
        }

        .header {
            padding-top: 20px;
            text-align: center;
        }
    </style>

    {% block script %}
        <script src="{% static 'clubManagement/js/attendance.js' %}"></script>
    {% endblock %}
{% endblock %}

clubManagement/templates/clubManagement/attendance_daily.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %} Add attendance {% endblock %}

{% block body %}
    {% include 'base/nav-bar.html' %}
    <div id="wrap">
        <div id="main">
            <div class="container">
                <h2 class="header">{{ head }}</h2>
                <div class="row form">
                {% csrf_token %}
                    {% for att in attendance_list %}
                        <div class="col-xs-6 col-sm-4 col-md-2 btn names {% if att.attendance %}btn-success{% else %}btn-danger{% endif %}"
                             id="{{ att.user.username }}_div" style="white-space: normal">
                            <p class="link">{{ att.user.first_name }} {{ att.user.last_name }}</p>
                        </div>
                    {% endfor %}
                    <p class="col-xs-12 col-md-12"></p>
                </div>
            </div>
        </div>
    </div>

    {% include 'base/footer.html' %}

    <style>
        .btn {
            margin: 10px;
        }

        .save-btn {
            padding: 10px 0;
        }

        .names {
            height: 80px;
        }



        .form {
            margin: 30px 0;
        }
        .header {
            padding-top: 20px;
            text-align: center;
        }

        .link {
            height: 100%;
            color: white;
            display: flex;
            align-items: center;
            justify-content: center;
        }
    </style>
{% endblock %}

clubManagement/templates/clubManagement/responsibility_confirm_delete.html
{% extends 'base/base.html' %}

{% block title %} Delete {% endblock %}

{% block body %}
    {% include 'base/nav-bar.html' %}
        <div id="wrap">
            <div id="main">
            <!-- content goes here -->
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <form class="card" action="" method="post" >
                                <div class="card-block">
                                    {% csrf_token %}
                                    <h2>Delete {{ object.name }}?</h2>
                                    <button type="submit" class="btn btn-danger">Yes, continue</button>
                                </div>
                            </form>
                            <a href="{% url 'responsibility_detail' object.id %}"><button class="btn btn-info">No, take me out of here</button></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% include 'base/footer.html' %}

    <style>
        .container {
            margin-top: 80px;
        }
    .btn {
        margin-right: 10px;
        margin-top: 20px;
    }
    </style>
{% endblock %}

clubManagement/templates/clubManagement/responsibility_detail.html
{% extends 'base/base.html' %}

{% block title %} {{ object.name }} {% endblock %}

{% load static %}

{% block script %}
    <!-- Latest compiled and minified JavaScript -->
{% endblock %}

{% block body %}
    {% include 'base/nav-bar.html' %}
        <div id="wrap">
            <div id="main">
            <!-- content goes here -->

                <div class="container">
                    <div class="row">

                        <div class="col-md-8">
                            <h3>Club Responsibility</h3>
                            <div class="card mb-3">
                              <img class="card-img-top" src="{% static 'clubManagement/image/great_power_great_responsibility.jpg' %}">
                              <div class="card-block">
                                <h4 class="card-title">{{ object.name }}</h4>
                                <p class="card-text">{{ object.description }}</p>
                                <p class="card-text">
                                    <small class="text-muted">
                                       Added by : {{ object.created_by.first_name }} {{ object.created_by.last_name }}
                                    </small>
                                </p>
                                  {% if edit_permission %}
                                <a href="{% url 'responsibility_update' object.id %}">
                                    <button type="submit" class="btn btn-primary add-btn">Update</button>
                                </a>
                                <a href="{% url 'responsibility_delete' object.id %}">
                                    <button type="submit" class="btn btn-danger add-btn">Delete</button>
                                </a>
                                  {% endif %}
                              </div>
                            </div>

                            <div class="card student-form" id="student-form" style="display: none">
                              <div class="card-block">
                                <form class="form-group col-md-6" action="" method="post">
                                    {% csrf_token %}
                                    <label for="exampleInputEmail1"><h4>Add Student</h4></label>
                                    <div class="dropdown">
                                        <input id="search" onkeyup="myFunction()" class="form-control" data-toggle="dropdown" placeholder="Search..." autocomplete="off">
                                        <input type="hidden" id="search-id" name="user_id">
                                        <div class="dropdown-menu" id="search-results">
                                            {% for user in all_users %}
                                                <p onclick="addText({{ user.id }}, '{{ user.first_name }} {{ user.last_name }}')" class="dropdown-item">{{ user.first_name }} {{ user.last_name }}</p>
                                            {% endfor %}
                                        </div>
                                    </div>
                                    <small id="emailHelp" class="form-text text-muted">Search for a student above.</small>
                                    <button type="submit" class="btn btn-secondary add-btn">Add</button>
                                  </form>
                              </div>
                            </div>
                        </div>

                        <ul class="list-group col-md-4">
                            <div class="margin-20"></div>
                            <li class="list-group-item justify-content-between">
                                <h5>Student's responsible</h5>
                                <span class="badge badge-default badge-pill">{{ user_count }}</span>
                              </li>
                            {% for resp in responsibility_list %}
                              <li class="list-group-item justify-content-between">
                                {{ resp.user.first_name }}  {{ resp.user.last_name }}
                                <form method="post" action="{% url "student_responsibility_delete" resp.id %}">
                                       {% csrf_token %}
                                      <button type="submit" class="close">×</button>
                                  </form>
                              </li>
                            {% endfor %}
                            {% if edit_permission %}
                            <div onclick="showForm()" class="col-md-6 offset-md-3">
                                <button class="btn btn-secondary add-btn">
                                    Add student
                                </button>
                            </div>
                            {% endif %}
                        </ul>

                    </div>
                </div>

            </div>
        </div>
    {% include 'base/footer.html' %}

    <style>
        .container {
            margin-top: 50px;
        }
        .add-btn {
            margin-top: 20px;
        }
        .margin-20 {
            margin: 24px;
        }
    </style>

    <script>
        function showForm() {
            var form = document.getElementById('student-form');
            if(form.style.display === 'none') {
                form.style.display = 'block';
            }
            else {
                form.style.display = 'none';
            }
        }

        function myFunction() {
            // Declare variables
            var input, filter, items, i;
            input = document.getElementById('search');
            filter = input.value.toUpperCase();
            items = document.getElementsByClassName('dropdown-item');

            // Loop through all list items, and hide those who don't match the search query
            for (i = 0; i < items.length; i++) {
                if (items[i].innerHTML.toUpperCase().indexOf(filter) > -1) {
                    items[i].style.display = "";
                } else {
                    items[i].style.display = "none";
                }
            }
        }

        function addText(id, name) {
            var inp1 = document.getElementById('search');
            var inp2 = document.getElementById('search-id');
            inp1.value = name;
            inp2.value = id;
        }
    </script>
{% endblock %}

clubManagement/templates/clubManagement/statusreport_confirm_delete.html
{#created by Rahul Krishnan, rahul.krishnan27@gmail.com#}
{% extends 'base/base.html' %}

{% block title %} Delete {% endblock %}

{% block body %}
    {% include 'base/nav-bar.html' %}
        <div id="wrap">
            <div id="main">
            <!-- content goes here -->
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <form class="card" action="" method="post" >
                                <div class="card-block">
                                    {% csrf_token %}
                                    <h2>Delete {{ object.name }}?</h2>
                                    <button type="submit" class="btn btn-danger">Yes, continue</button>
                                </div>
                            </form>
                            <a href="{% url 'status_detail' object.id %}"><button class="btn btn-info">No, take me out of here</button></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% include 'base/footer.html' %}

    <style>
        .container {
            margin-top: 80px;
        }
    .btn {
        margin-right: 10px;
        margin-top: 20px;
    }
    </style>
{% endblock %}

clubManagement/templates/clubManagement/statusreport_detail.html
{#created by Rahul Krishnan, rahul.krishnan27@gmail.com#}
{% extends 'base/base.html' %}

{% block title %} {{ object.name }} {% endblock %}

{% load static %}

{% block css %}
    <script src="{% static 'base/js/tinymce/tinymce.min.js' %}"></script>
    <script>
        tinymce.init({
            selector: 'textarea',
            height: 300,
            menubar: false,
            entity_encoding: "raw",
            readonly: 1,
            statusbar: false,
            branding: false,
            toolbar: false,
        });
    </script>
{% endblock %}

{% block script %}
    <!-- Latest compiled and minified JavaScript -->
{% endblock %}

{% block body %}
    {% include 'base/nav-bar.html' %}
        <div id="wrap">
            <div id="main">
            <!-- content goes here -->

                <div class="container">
                    <div class="row">
                        <div class="col-md-8">
                            <h1>Status update</h1>
                            <h5 class="text-muted">{{ object.user.first_name }} {{ object.user.last_name }}</h5>
                            <hr>
                            <div class="card mb-3">
                            {% if object.image %}
                                <img class="card-img-top img-fluid" src="/static/media/{{ object.image }}">
                            {% else %}
                                <img class="card-img-top img-fluid" src="{% static 'clubManagement/image/status.png' %}">
                            {% endif %}
                              <div class="card-block">
                                <h4 class="card-title">{{ object.title }}</h4>
                                <p class="card-text">
                                    <textarea type="text" class="form-control" name="content" id="id_content">
                                        {{ object.content }}
                                    </textarea>
                                </p>
                                <p class="card-text">
                                    <small class="text-muted">
                                       Added by : {{ object.user.first_name }} {{ object.user.last_name }}
                                    </small>
                                </p>
                                  {% if edit_permission %}
                                    <a href="{% url 'status_update' object.id %}">
                                        <button type="submit" class="btn btn-primary add-btn">Update</button>
                                    </a>
                                    <a href="{% url 'status_delete' object.id %}">
                                        <button type="submit" class="btn btn-danger add-btn">Delete</button>
                                    </a>
                                  {% endif %}
                              </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    {% include 'base/footer.html' %}

    <style>
        .container {
            margin-top: 50px;
        }
        .add-btn {
            margin-top: 20px;
        }
        .margin-20 {
            margin: 24px;
        }
        .mceu_12 {
            display: none;
        }
        .mce-panel {
            border: none;
            background-color: white;
        }
    </style>

{% endblock %}

clubManagement/templates/clubManagement/statusreport_form.html
{#created by Rahul Krishnan, rahul.krishnan27@gmail.com#}
{% extends 'base/base.html' %}
{% load static %}
{% block title %} Status {% endblock %}


{% block body %}
    {% include 'base/nav-bar.html' %}
    <div id="wrap">
        <div id="main">
            <!-- content goes here -->
            <div class="container">
                <div class="row">
                    <div class="col-md-8 offset-md-2 card">
                        <div class="card-block">
                            <h1 class="card-title">Status</h1>
                            <hr>
                            <form action="" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <small class="form-text text-muted">
                                    Content
                                </small>
                                <div class="form-group">
                                    <label for="name">Title</label>
                                    <input type="text" class="form-control" name="title" id="name"
                                           value="{{ object.title }}" placeholder="Title">
                                    <small class="form-text text-muted">
                                        Title of the article
                                    </small>
                                </div>
                                <div class="form-group">
                                    <textarea type="text" class="form-control" name="content" id="id_content">
                                        {{ object.content }}
                                    </textarea>
                                </div>

                                <div class="form-group">
                                    <small class="form-text text-muted">
                                        Project
                                    </small>
                                    <select name="project" class="form-control" id="id_project">
                                        <option value="">None</option>
                                        {% for i in project %}
                                            <option value="{{ i.id }}">{{ i }}</option>
                                        {% endfor %}
                                    </select>
                                </div>

                                <div class="form-group">
                                    <input id="id_image" name="image" value="{{ object.image }}"
                                           type='file' class="form-control"/>

                                </div>
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% include 'base/footer.html' %}

    <div class="notifications">
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger alert-dismissable">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                        {{ field.label }}: {{ error|escape }}
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger alert-dismissable">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                    {{ error|escape }}
                </div>
            {% endfor %}
        {% endif %}
    </div>

    <style>
        .container {
            margin-top: 70px;
        }

        .notifications {
            position: fixed;
            top: 90px;
            right: 0;
            z-index: 1000;
            font-size: 0.7em;
            max-width: 90%;
        }

        body {
            background-color: #fcfcfc;
        }
    </style>
   <script src="{% static 'base/js/tinymce/tinymce.min.js' %}"></script>
    <script>
        tinymce.init({
            selector: 'textarea',
            height: 300,
            menubar: false,
            entity_encoding: "raw",
            plugins: [
                'advlist autolink lists link image charmap print preview anchor',
                'searchreplace visualblocks code fullscreen',
                'insertdatetime media table contextmenu paste code'
            ],
            toolbar: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter ' +
            'alignright alignjustify | bullist numlist outdent indent | link image',
            statusbar: false,
            branding: false
        });
    </script>


{% endblock %}